### ISSUE TITLE
rust example

### ISSUE THREAD

**Issue by overheat** [awslabs/aws-crt-ffi#45]
Examples for s3 and iot.

**Comment by yasminetalby** [comment]
Hello @overheat ,

Thank you very much for your submission and feedback. I sincerely apologies for the delay of our answer. 
Is there any specific example you would like to see?

Best regards,

Yasmine

**Comment by ghost** [comment]
Looks, there is no mqtt/iot/s3 submodules under `crt` folder. Any plan to support those libs?

**Comment by overheat** [comment]
> Hello @overheat ,
> 
> Thank you very much for your submission and feedback. I sincerely apologies for the delay of our answer. Is there any specific example you would like to see?
> 
> Best regards,
> 
> Yasmine

@yasminetalby example for S3 put.

**Comment by jmklix** [comment]
Sorry, but I don't think we are going to add a rust example here for s3 puts. But the aws-sdk-rust is now GA and we have a [sample there](https://github.com/awslabs/aws-sdk-rust/blob/main/examples/examples/s3/src/s3-service-lib.rs#L123) that shows you how to use put_object in rust. Closing this issue, but please feel free to open a new issue if you have any more questions/concerns.
