### ISSUE TITLE
README is generic

### ISSUE THREAD

**Issue by hyandell** [awslabs/aws-crt-ffi#46]
Please fill the README out with some content.

**Comment by yasminetalby** [comment]
Hello @hyandell,

I apologies for the delay of our answer. Thank you very much for your submission and feedback.

Is there any specific information you would like to be documented in the README.md?

Best regards,

Yasmine

**Comment by nateprewitt** [comment]
I've added https://github.com/awslabs/aws-crt-ffi/pull/58 to at least fix the base issues of the name and minimal description. @yasminetalby can we get someone from the CRT team to take a look?

I've also listed a few other things that we should consider adding in a follow up PR.

**Comment by yasminetalby** [comment]
Thank you very much for your contribution @nateprewitt. We really appreciate your time and support in improving the aws-crt-ffi repository documentation.

I will close this issue as the PR has been merged.

If you have any further request or inquiries please let me know!

Best regards,

Yasmine
